# Generated by Django 2.2.2 on 2019-06-25 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.TextField(default=uuid.uuid4, max_length=40),
        ),
    ]
